;; Auto-generated by Emacs Custom system. Edit with care.
(custom-set-variables
 '(custom-enabled-themes '(gruber-darker))
 '(custom-safe-themes
   '("e13beeb34b932f309fb2c360a04a460821ca99fe58f69e65557d6c1b10ba18c7" default))
 '(package-selected-packages
   '(ag cmake-mode company dash dash-functional elpy exec-path-from-shell
        gruber-darker-theme haskell-mode helm helm-git-grep helm-ls-git
        ido-completing-read+ magit move-text multiple-cursors org-cliplink
        paredit php-mode proof-general purescript-mode racket-mode
        rust-mode scala-mode smex tide typescript-mode yasnippet)))
(custom-set-faces)
